#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

wmakeLnInclude  library
wmakeLnInclude  solver

export WM_NCOMPPROCS=6

wmake $makeType library
wmake solver/soilFoam
wmake solver/soilDyMFoam

doxygen ../.doxygen_cfg > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file
